# Site settings
course_name: INF721 - Aprendizado em Redes Neurais Profundas
course_description: "Esse curso é uma introdução aos fundamentos e técnicas modernas de Deep Learning, possibilitando-os projetar e implementar redes neurais profundas para classificação e regressão de dados estruturados (tabulares) e não-estruturados (imagens, texto, áudio, etc)."
course_semester: "2023/2"

baseurl: "/ufv-inf721" # the subpath of your site, e.g. /blog/
url: "https://lucasnfe.github.io/" # the base hostname & protocol for your site

schoolname: "Universidade Federal de Viçosa"
schoolurl: "https://www.ufv.br"
twitter_username: lucasnfe 

address: |
    Departamento de Informática
    Universidade Federal de Viçosa
    Viçosa, MG, Brasil

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
